'use strict';
const q=id=>document.getElementById(id),time=q('time'),story=q('story'),world=q('world');
let DATA=window.HISTORY_DATA;
const SVG_NS='http://www.w3.org/2000/svg';
const ENUMS={presence:['documented','probable','uncertain','traditional'],provenance:['documented movement','plausible','unknown'],continuity:['growing','stable','contracting','evidence becomes uncertain','documented displacement','documented destruction'],evidence:['well documented','historically established, details uncertain','reconstructed','traditional account'],concentration:['very small','small','substantial','major','dominant center'],movementType:['forced removal','expulsion','flight','voluntary migration','return / Aliyah'],cause:['war','conquest','persecution','antisemitic violence','economic opportunity','trade','religious motivation','political/national movement','family/community ties','other','uncertain'],changeCause:['natural increase','forced conversion','documented displacement','violent destruction','mortality','evidence becomes uncertain','display transition','other','uncertain']};
function validateHistory(data){
 const errors=[],required=['places','populations','populationChanges','movements','communityDestructions','historicalEvents','sources','eras','cameraStates'];
 const fail=m=>errors.push(m),finite=x=>typeof x==='number'&&Number.isFinite(x),coords=x=>Array.isArray(x)&&x.length===2&&x.every(finite);
 for(const key of required)if(!Array.isArray(data[key]))fail(key+' must be an array');if(errors.length)return errors;
 const sets={};for(const key of required){const ids=new Set();for(const r of data[key]){if(!r.id&&!['eras','cameraStates'].includes(key))fail(key+': missing id');if(r.id&&ids.has(r.id))fail(key+': duplicate id '+r.id);if(r.id)ids.add(r.id);}sets[key]=ids;}
 const places=new Map(data.places.map(p=>[p.id,p]));
 function hasEnum(value,key,name){if(!ENUMS[key].includes(value))fail(name+': invalid '+key+' '+value);}
 function refs(r){for(const id of r.sourceIds||[])if(!sets.sources.has(id))fail(r.id+': unknown source '+id);}
 function dates(r){if(!finite(r.startDate))fail(r.id+': invalid startDate');if(r.endDate!=null&&(!finite(r.endDate)||r.endDate<r.startDate))fail(r.id+': invalid endDate');}
 function estimate(e,id){if(!e)return;for(const k of ['lowEstimate','highEstimate','preferredEstimate'])if(e[k]!=null&&(!finite(e[k])||e[k]<0))fail(id+': invalid '+k);if(e.lowEstimate!=null&&e.highEstimate!=null&&e.lowEstimate>e.highEstimate)fail(id+': reversed estimate range');if(e.preferredEstimate!=null&&((e.lowEstimate!=null&&e.preferredEstimate<e.lowEstimate)||(e.highEstimate!=null&&e.preferredEstimate>e.highEstimate)))fail(id+': preferred estimate outside range');if([e.lowEstimate,e.highEstimate,e.preferredEstimate].some(v=>v!=null)&&!(e.sourceIds||[]).length)fail(id+': numbered estimate requires sources');}
 for(const p of data.places)if(p.coordinates!=null&&!coords(p.coordinates))fail(p.id+': invalid coordinates');
 for(const p of data.populations){dates(p);refs(p);hasEnum(p.presenceStatus,'presence',p.id);hasEnum(p.provenanceStatus,'provenance',p.id);hasEnum(p.continuityStatus,'continuity',p.id);hasEnum(p.concentration,'concentration',p.id);if(!places.has(p.place))fail(p.id+': unknown place');if(places.get(p.place)?.role==='killing site')fail(p.id+': a killing site cannot become a population node');if(p.endDate!=null&&!['documented displacement','documented destruction','forced conversion','documented absence'].includes(p.endReason))fail(p.id+': an end date requires an explicit supported endReason');estimate(p.estimate,p.id);for(const id of p.movementIds||[])if(!sets.movements.has(id))fail(p.id+': unknown movement '+id);let prev=-Infinity;for(const s of p.states||[]){if(!finite(s.date)||s.date<prev)fail(p.id+': unsorted state dates');prev=s.date;if(s.concentration)hasEnum(s.concentration,'concentration',p.id);if(s.presenceStatus)hasEnum(s.presenceStatus,'presence',p.id);if(s.continuityStatus)hasEnum(s.continuityStatus,'continuity',p.id);}}
 for(const c of data.populationChanges){dates(c);refs(c);if(!sets.populations.has(c.populationId))fail(c.id+': unknown population');hasEnum(c.populationChangeCause,'changeCause',c.id);if(c.result?.concentration)hasEnum(c.result.concentration,'concentration',c.id);if(c.result?.presenceStatus)hasEnum(c.result.presenceStatus,'presence',c.id);if(c.result?.intensity!=null&&(!finite(c.result.intensity)||c.result.intensity<0||c.result.intensity>1))fail(c.id+': invalid visual intensity');if(c.populationChangeCause==='evidence becomes uncertain'&&c.result?.intensity===0)fail(c.id+': uncertain evidence must not erase presence');}
 for(const m of data.movements){refs(m);if(m.movementType!=null)hasEnum(m.movementType,'movementType',m.id);else if(m.movementTypeConfidence!=='uncertain')fail(m.id+': unknown movement type requires an explicit uncertainty qualification');hasEnum(m.cause,'cause',m.id);hasEnum(m.evidenceStatus,'evidence',m.id);hasEnum(m.provenanceStatus,'provenance',m.id);if(m.origin!=null&&!places.has(m.origin))fail(m.id+': unknown origin');if(m.destination!=null&&!places.has(m.destination))fail(m.id+': unknown destination');if(m.originCoordinates!=null&&!coords(m.originCoordinates))fail(m.id+': invalid origin coordinates');if(m.destinationCoordinates!=null&&!coords(m.destinationCoordinates))fail(m.id+': invalid destination coordinates');for(const id of m.intermediateLocations||[])if(!places.has(id))fail(m.id+': unknown intermediate location');for(const id of m.linkedDestructionIds||[])if(!sets.communityDestructions.has(id))fail(m.id+': unknown destruction');if(m.evidenceStatus!=='traditional account'&&m.provenanceStatus==='documented movement'&&!(m.sourceIds||[]).length)fail(m.id+': documented movement requires sources');estimate({lowEstimate:m.populationLow,highEstimate:m.populationHigh,preferredEstimate:m.populationPreferred,sourceIds:m.sourceIds},m.id);estimate(m.reportedEstimate,m.id);const w=m.rendering?.window;if(w&&(!Array.isArray(w)||w.length!==3||!w.every(finite)||w[0]>w[1]||w[1]>w[2]))fail(m.id+': invalid movement visibility window');}
 for(const c of data.communityDestructions){dates(c);refs(c);if(!sets.populations.has(c.populationId)||!places.has(c.place))fail(c.id+': unknown community or place');if(c.destructionStatus!=='documented violent community destruction')fail(c.id+': murdered-community symbol requires violent destruction of the community itself');if(!(c.sourceIds||[]).length)fail(c.id+': community destruction requires sources');if(c.reestablishedDate!=null&&(!finite(c.reestablishedDate)||c.reestablishedDate<c.startDate))fail(c.id+': invalid reestablishment date');}
 for(const e of data.historicalEvents){refs(e);if(!places.has(e.place))fail(e.id+': unknown event place');}
 if(!data.timeline||!finite(data.timeline.start)||!finite(data.timeline.end)||data.timeline.start>=data.timeline.end)fail('Invalid timeline endpoints');
 return errors;
}
function assertHistory(data){const errors=validateHistory(data);if(errors.length)throw new Error('Historical dataset: '+errors.join('; '));}
function indexData(data){return {places:new Map(data.places.map(p=>[p.id,p])),sources:new Map(data.sources.map(s=>[s.id,s]))};}
assertHistory(DATA);let INDEX=indexData(DATA);
function svg(tag,attrs,parent){const e=document.createElementNS(SVG_NS,tag);for(const [k,v] of Object.entries(attrs))if(v!=null)e.setAttribute(k,v);parent.appendChild(e);return e;}
function vis(el,opacity){if(!el)return;if(el._opacity!==opacity){el.style.opacity=opacity;el._opacity=opacity;}const interactive=opacity>.08,hidden=opacity===0;if(el._interactive!==interactive){el.style.pointerEvents=interactive?'auto':'none';el.setAttribute('tabindex',interactive?'0':'-1');el._interactive=interactive;}if(el._hidden!==hidden){el.setAttribute('aria-hidden',hidden?'true':'false');el._hidden=hidden;}}
function yearLabel(y){return y<0?Math.abs(y)+' BCE':y===0?'1 BCE / 1 CE':y+' CE';}
function fw(y,s,p,n){if(y<s||y>n)return 0;if(y<=p)return Math.max(.12,(y-s)/(p-s||1));return Math.max(0,1-(y-p)/(n-p||1));}
function lastState(y,states,key='date'){let found=null;for(const s of states||[])if(s[key]<=y&&(!found||s[key]>=found[key]))found=s;return found;}
function activeAt(r,y){return y>=r.startDate&&(r.endDate==null||y<r.endDate);}
function opacityAt(y,states,smooth=0){let last=-1;for(let i=0;i<(states||[]).length;i++)if(y>=states[i][0])last=i;if(last<0)return 0;const [date,value]=states[last];if(!smooth||last===0)return value;const before=states[last-1][1],t=Math.min(1,Math.max(0,(y-date)/smooth));return before+(value-before)*t;}
// Source-attested routes alone may render. Unknown endpoints never get invented.
function movementWindow(m){if(m.rendering?.window)return m.rendering.window;const start=m.dateRange?.start??m.eventDateRange?.start,end=m.dateRange?.end??start;if(!Number.isFinite(start))return null;return [start-8,(start+end)/2,end+8];}
function canRenderMovement(m,data=DATA){if(m.rendering?.enabled===false||!movementWindow(m))return false;const idx=data===DATA?INDEX:indexData(data);const origin=m.originCoordinates||idx.places.get(m.origin)?.coordinates,dest=m.destinationCoordinates||idx.places.get(m.destination)?.coordinates;return !!(origin&&dest&&(m.destination!=null||m.regionalDisplacement===true)&&(m.evidenceStatus==='traditional account'||(m.provenanceStatus==='documented movement'&&(m.sourceIds||[]).length>0&&['well documented','historically established, details uncertain'].includes(m.evidenceStatus))));}
function movementColor(m,data=DATA){const traditional=m.evidenceStatus==='traditional account';if(traditional)return '#6d6256';const destination=data.places.find(p=>p.id===m.destination);if(destination?.isLandOfIsrael)return '#275d9b';if(['forced removal','expulsion','flight'].includes(m.movementType)||['persecution','antisemitic violence'].includes(m.cause))return '#a33b32';return '#6d6256';}
function resolvePopulation(p,y,data=DATA){
 const status={presenceStatus:p.presenceStatus,concentration:p.concentration,continuityStatus:p.continuityStatus,...lastState(y,p.states)};
 const applicable=data.populationChanges.filter(c=>c.populationId===p.id&&activeAt(c,y)).sort((a,b)=>a.startDate-b.startDate);
 for(const c of applicable)if(c.result)Object.assign(status,c.result);
 const render=p.rendering||{},within=y>=p.startDate&&(p.endDate==null||y<=p.endDate)&&y>=(render.displayStart??-Infinity)&&(render.displayEnd==null||y<render.displayEnd);
 let intensity=render.densityOpacityStates?.length?opacityAt(y,render.densityOpacityStates,render.transitionYears||0):data.concentrationStyles?.[status.concentration]??.28;
 let nodeOpacity=render.nodeOpacityStates?.length?opacityAt(y,render.nodeOpacityStates):1;
 if(render.nodeRamp){const [start,duration,base,end=Infinity]=render.nodeRamp;if(y>=start&&y<=end)nodeOpacity=Math.min(1,(y-start)/duration+base);}
 if(!render.densityOpacityStates?.length){const categoryStates=[[p.startDate,data.concentrationStyles?.[p.concentration]??.28],...(p.states||[]).filter(s=>s.concentration).map(s=>[s.date,data.concentrationStyles?.[s.concentration]??.28])].sort((a,b)=>a[0]-b[0]);intensity=opacityAt(y,categoryStates,render.transitionYears??8);for(const c of applicable){if(c.result?.concentration){const target=data.concentrationStyles?.[c.result.concentration]??.28,t=Math.min(1,Math.max(0,(y-c.startDate)/(c.result.transitionYears??8)));intensity=intensity+(target-intensity)*t;}}}if(status.intensity!=null)intensity=status.intensity;if(status.nodeOpacity!=null)nodeOpacity=status.nodeOpacity;
 const uncertain=status.uncertain||status.presenceStatus==='uncertain'||status.continuityStatus==='evidence becomes uncertain'||(render.uncertainAfter!=null&&y>render.uncertainAfter);
 // Documentary silence cannot be rendered as extinction.
 if(uncertain&&within)intensity=Math.max(.09,intensity);
 return {id:p.id,...status,intensity:within?intensity:0,nodeOpacity:within?nodeOpacity:0,uncertain:!!uncertain,visible:within,changes:applicable};
}
function computeFrame(y,data=DATA){
 return {year:y,populations:data.populations.map(p=>resolvePopulation(p,y,data)),movements:data.movements.map(m=>({id:m.id,visible:canRenderMovement(m,data),opacity:canRenderMovement(m,data)?fw(y,...(movementWindow(m)||[0,0,0]))*(m.rendering?.opacity??1):0,color:movementColor(m,data)})),destructions:data.communityDestructions.map(c=>({id:c.id,visible:c.destructionStatus==='documented violent community destruction'&&activeAt(c,y)&&(c.reestablishedDate==null||y<c.reestablishedDate)})),events:data.historicalEvents.map(e=>({id:e.id,opacity:e.rendering?.window?fw(y,...e.rendering.window):0})),changes:data.populationChanges.filter(c=>activeAt(c,y)),camera:lastState(y,data.cameraStates,'startDate'),era:lastState(y,data.eras,'startDate')};
}
// All map objects are projections of records; no populations are manufactured from route endpoints.
function ribbon(a,c,b,width=9,head=28){
 const point=t=>[(1-t)*(1-t)*a[0]+2*(1-t)*t*c[0]+t*t*b[0],(1-t)*(1-t)*a[1]+2*(1-t)*t*c[1]+t*t*b[1]];
 const samples=Array.from({length:65},(_,i)=>point(i/64));let cut=63,length=0;while(cut>1&&length<head){length+=Math.hypot(samples[cut+1][0]-samples[cut][0],samples[cut+1][1]-samples[cut][1]);cut--;}
 const normal=i=>{const p=samples[Math.max(0,i-1)],n=samples[Math.min(64,i+1)],dx=n[0]-p[0],dy=n[1]-p[1],l=Math.hypot(dx,dy)||1;return [-dy/l,dx/l];};
 const offset=(i,w)=>{const n=normal(i);return [samples[i][0]+n[0]*w,samples[i][1]+n[1]*w];};const left=[],right=[];for(let i=0;i<=cut;i++){left.push(offset(i,width/2));right.push(offset(i,-width/2));}
 return [...left,offset(cut,width*1.45),b,offset(cut,-width*1.45),...right.reverse()].map(p=>p.map(v=>v.toFixed(1)).join(',')).join(' ');
}
// One path contains the traditional dotted arc and its integrated triangular outline.
function traditionalArc(a,c,b){const dx=b[0]-c[0],dy=b[1]-c[1],l=Math.hypot(dx,dy)||1,u=[dx/l,dy/l],n=[-u[1],u[0]],back=[b[0]-u[0]*17,b[1]-u[1]*17],left=[back[0]+n[0]*8,back[1]+n[1]*8],right=[back[0]-n[0]*8,back[1]-n[1]*8];return `M ${a} Q ${c} ${b} L ${left} L ${right} L ${b}`;}
function bind(el,record,type){el._record=record;el._recordType=type;el.setAttribute('role','button');el.setAttribute('aria-label',record.title||record.historicalPlaceName||record.id);el.dataset.title=record.title||record.historicalPlaceName||record.id;const open=()=>{if(mapNavigation.pointers.size||(typeof performance!=='undefined'&&performance.now()<mapNavigation.suppressUntil))return;showStory(record,type);};el.addEventListener('click',open);el.addEventListener('mouseenter',()=>{if(window.matchMedia&&window.matchMedia('(hover: hover) and (pointer: fine) and (min-width: 701px)').matches)open();});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});}
const rendered={populations:new Map(),movements:new Map(),destructions:new Map(),events:new Map(),conversions:new Map()};
function renderRecords(){
 let anchors=q('anchorLayer');if(!anchors)anchors=svg('g',{id:'anchorLayer'},world);anchors.replaceChildren();let labels=q('labelLayer');if(!labels)labels=svg('g',{id:'labelLayer'},world);labels.replaceChildren();
 for(const map of Object.values(rendered))map.clear();q('populationLayer').replaceChildren();q('movementLayer').replaceChildren();let layers=q('eventLayer');if(!layers)layers=svg('g',{id:'eventLayer'},world);layers.replaceChildren();let memorials=q('memorialLayer');if(!memorials)memorials=svg('g',{id:'memorialLayer'},world);memorials.replaceChildren();
 const defs=world.querySelector('defs');if(!q('uncertainPopulationPattern')){const pattern=svg('pattern',{id:'uncertainPopulationPattern',width:7,height:7,patternUnits:'userSpaceOnUse'},defs);svg('rect',{width:7,height:7,fill:'#245b93','fill-opacity':.4},pattern);svg('path',{d:'M-1,1 L1,-1 M0,7 L7,0 M6,8 L8,6',stroke:'#245b93','stroke-width':1.5},pattern);}
 for(const p of DATA.populations){const place=INDEX.places.get(p.place),r=p.rendering||{},footprint=p.geographicFootprint||place.geographicFootprint;let density=null,node=null,underlay=null,label=null;if(footprint){underlay=svg('path',{class:'populationUnderlay',d:footprint,fill:'#f1e6ce','clip-path':'url(#landClip)',style:'pointer-events:none',opacity:0},q('populationLayer'));density=svg('path',{id:r.densityId||p.id+'Density',class:'density','clip-path':'url(#landClip)',d:footprint,opacity:0},q('populationLayer'));bind(density,p,'population');}const anchor=p.coordinates||place.coordinates;if(r.node!==false&&anchor){node=svg('g',{id:p.id},anchors);node._anchor=anchor;if(r.ring)svg('circle',{class:'ring',cx:anchor[0],cy:anchor[1],r:11},node);svg('circle',{class:'dot',cx:anchor[0],cy:anchor[1],r:r.radius||5},node);bind(node,p,'population');label=makeMapLabel(p,'population',anchor,r.label||p.historicalPlaceName,r.labelPosition,labels);}rendered.populations.set(p.id,{density,node,underlay,label});}
 for(const m of DATA.movements){if(!canRenderMovement(m))continue;const a=m.originCoordinates||INDEX.places.get(m.origin).coordinates,b=m.destinationCoordinates||INDEX.places.get(m.destination).coordinates,c=m.rendering?.control||[(a[0]+b[0])/2,(a[1]+b[1])/2];const traditional=m.evidenceStatus==='traditional account',color=movementColor(m),attrs={id:m.id,class:traditional?'biblical':'route',fill:traditional?'none':color};if(traditional)attrs.d=traditionalArc(a,c,b);else{const width=m.movementScale?{small:7,substantial:9,major:13,massive:18}[m.movementScale]||9:m.rendering?.width||9;attrs.points=ribbon(a,c,b,width,m.rendering?.headLength||28);attrs.stroke=color;attrs['stroke-width']=4.5;attrs.style='filter:drop-shadow(0 2px 1.5px #00000035)';}const el=svg(traditional?'path':'polygon',attrs,q('movementLayer'));bind(el,m,'movement');rendered.movements.set(m.id,el);}
 for(const e of DATA.historicalEvents){const r=e.rendering||{},a=r.position||INDEX.places.get(e.place)?.coordinates;if(!a)continue;const g=svg('g',{id:e.id},layers);g._anchor=a;svg('circle',{class:'dot',cx:a[0],cy:a[1],r:r.radius||5},g);g._label=makeMapLabel(e,'event',a,r.label||e.title,r.labelPosition,labels);bind(g,e,'event');rendered.events.set(e.id,g);}
 for(const c of DATA.communityDestructions){if(c.destructionStatus!=='documented violent community destruction')continue;const a=c.rendering?.position||INDEX.places.get(c.place)?.coordinates;if(!a)continue;const leader=svg('path',{class:'mapLeader memorialLeader',d:''},memorials),g=svg('g',{id:c.id,class:'memorial',transform:`translate(${a})`},memorials);g._anchor=a;g._leader=leader;svg('circle',{r:17,fill:'#fffaf0',stroke:'#a33b32','stroke-width':1.3},g);svg('path',{d:'M0,-11 L-9.5,5.5 L9.5,5.5 Z M0,11 L-9.5,-5.5 L9.5,-5.5 Z',fill:'none',stroke:'#8f2f29','stroke-width':2.2,'stroke-linejoin':'round'},g);svg('path',{d:'M-12,-1 L-5,2 L-1,-1 L4,2 L12,-1',fill:'none',stroke:'#fffaf0','stroke-width':3.7},g);svg('title',{},g).textContent=c.title;bind(g,c,'destruction');rendered.destructions.set(c.id,g);}
 let conversions=q('conversionLayer');if(!conversions)conversions=svg('g',{id:'conversionLayer'},world);conversions.replaceChildren();
 for(const change of DATA.populationChanges){if(!canRenderConversion(change))continue;const population=DATA.populations.find(p=>p.id===change.populationId),a=change.rendering?.position||population?.coordinates||INDEX.places.get(population?.place)?.coordinates;if(!a)continue;const leader=svg('path',{class:'mapLeader memorialLeader',d:''},conversions),g=svg('g',{id:'conversion-'+change.id,class:'memorial conversionSymbol'},conversions);g._anchor=a;g._leader=leader;g._record=change;drawCommunitySymbol(g,true);bind(g,change,'change');rendered.conversions.set(change.id,g);}
 for(const symbol of rendered.destructions.values())drawCommunitySymbol(symbol,false);initSymbolKey();
 world.appendChild(anchors);world.appendChild(layers);world.appendChild(memorials);world.appendChild(conversions);world.appendChild(labels);
}
function canRenderConversion(change){return change.populationChangeCause==='forced conversion'&&(change.sourceIds||[]).length>0&&['well documented','historically established, details uncertain'].includes(change.evidenceStatus);}
const SYMBOL_SHAPES={octagon:'M15.71,6.51 L6.51,15.71 L-6.51,15.71 L-15.71,6.51 L-15.71,-6.51 L-6.51,-15.71 L6.51,-15.71 L15.71,-6.51 Z',diamond:'M0,-17.4 L17.4,0 L0,17.4 L-17.4,0 Z'};let symbolClipCount=0;
function hexagramPath(r){const h=(r*.866).toFixed(2),q=(r/2).toFixed(2);return `M0,${-r} L${h},${q} L-${h},${q} Z M0,${r} L-${h},-${q} L${h},-${q} Z`;}
// Map symbols: shape + color carry the meaning (never color alone). Murdered community = red octagon; forced conversion = purple diamond; to Christianity = split diamond, half star / half cross.
function drawCommunitySymbol(group,conversion){for(const child of [...group.children])if(child.tagName.toLowerCase()!=='title')child.remove();group.dataset.symbol=conversion?'forced-conversion':'violent-community-destruction';const cream='#FFF3DC',purple='#5A3B7A',outline={class:'symbolShape',stroke:'#1B2328','stroke-width':1.2,'stroke-linejoin':'round'},starLine={fill:'none',stroke:cream,'stroke-width':1.5,'stroke-linejoin':'round'};if(!conversion){svg('path',{...outline,d:SYMBOL_SHAPES.octagon,fill:'#8C2A24'},group);svg('path',{...starLine,d:hexagramPath(10.4)},group);return;}if(group._record?.conversionReligion!=='Christianity'){svg('path',{...outline,d:SYMBOL_SHAPES.diamond,fill:purple},group);svg('path',{...starLine,d:hexagramPath(8.4)},group);return;}group.setAttribute('data-conversion-religion','Christianity');const left='symbolClip'+(++symbolClipCount),right='symbolClip'+(++symbolClipCount),defs=svg('defs',{},group);svg('rect',{x:-20,y:-20,width:20,height:40},svg('clipPath',{id:left},defs));svg('rect',{x:0,y:-20,width:20,height:40},svg('clipPath',{id:right},defs));svg('path',{d:SYMBOL_SHAPES.diamond,fill:purple,'clip-path':`url(#${left})`},group);svg('path',{d:SYMBOL_SHAPES.diamond,fill:cream,'clip-path':`url(#${right})`},group);svg('path',{...outline,d:SYMBOL_SHAPES.diamond,fill:'none'},group);svg('path',{...starLine,d:hexagramPath(10.6),'clip-path':`url(#${left})`},group);svg('path',{d:'M1,-10.6 V10.6 M1,-3.6 H9.2',fill:'none',stroke:purple,'stroke-width':1.8,'stroke-linecap':'square'},group);}
function initSymbolKey(){const old=world.ownerSVGElement.parentElement.querySelector('.legendStar');if(old)drawCommunitySymbol(old,false);if(q('conversionLegend'))return;const row=document.createElement('div');row.id='conversionLegend';const icon=document.createElementNS(SVG_NS,'svg');icon.setAttribute('class','legendStar');icon.setAttribute('viewBox','-18 -18 36 36');icon.setAttribute('aria-hidden','true');drawCommunitySymbol(icon,true);row.appendChild(icon);row.appendChild(document.createTextNode('Forced conversion, other or unknown faith'));q('legendContents').appendChild(row);const christianRow=document.createElement('div'),christianIcon=document.createElementNS(SVG_NS,'svg');christianIcon.setAttribute('class','legendStar');christianIcon.setAttribute('viewBox','-18 -18 36 36');christianIcon.setAttribute('aria-hidden','true');christianIcon._record={conversionReligion:'Christianity'};drawCommunitySymbol(christianIcon,true);christianRow.appendChild(christianIcon);christianRow.appendChild(document.createTextNode('Forced conversion to Christianity'));q('legendContents').appendChild(christianRow);}
function makeMapLabel(record,type,anchor,title,position,parent){const group=svg('g',{class:'labelAnchor'},parent);group._anchor=anchor;group._labelSide=record.rendering?.labelSide;group._leader=svg('path',{class:'mapLeader',d:''},group);const xy=position||[anchor[0]+10,anchor[1]-8];svg('text',{class:'place',x:xy[0],y:xy[1]},group).textContent=title;bind(group,record,type);return group;}
let timelineYears=[],timelinePositions=[];
function buildTimeline(){timelineYears=[];timelinePositions=[];let distance=0;const config=DATA.timeline,dates=[...DATA.populations.flatMap(p=>(p.states||[]).map(s=>s.date)),...DATA.populationChanges.map(c=>c.startDate),...DATA.historicalEvents.map(e=>e.dateRange.start)];for(let y=config.start;y<=config.end;y++){timelineYears.push(y);timelinePositions.push(distance);const move=Math.max(0,...DATA.movements.filter(m=>canRenderMovement(m)).map(m=>fw(y,...movementWindow(m))));const change=Math.max(0,...dates.map(date=>Math.max(0,1-Math.abs(y-date)/config.changeRadius)));distance+=config.quietWeight+config.movementWeight*move+config.changeWeight*change;}const total=timelinePositions.at(-1);timelinePositions=timelinePositions.map(p=>p/total*config.range);time.min=0;time.max=config.range;time.step=1;renderNotches();q('timelineTicks').replaceChildren();for(const year of config.ticks||[config.start,config.end]){if(year<config.start||year>config.end)continue;const label=document.createElement('span');label.textContent=yearLabel(year);label.style.left=positionForYear(year)/config.range*100+'%';q('timelineTicks').appendChild(label);}}
function positionForYear(year){return timelinePositions[Math.max(0,Math.min(timelineYears.length-1,Math.round(year)-DATA.timeline.start))];}
function yearForPosition(position){const value=Math.max(0,Math.min(DATA.timeline.range,+position));let lo=0,hi=timelinePositions.length-1;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(timelinePositions[mid]<value)lo=mid+1;else hi=mid;}if(lo>0&&value-timelinePositions[lo-1]<timelinePositions[lo]-value)lo--;return timelineYears[lo];}
function continuousYear(position){const value=Math.max(0,Math.min(DATA.timeline.range,+position));let lo=0,hi=timelinePositions.length-1;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(timelinePositions[mid]<value)lo=mid+1;else hi=mid;}if(lo===0)return timelineYears[0];const a=timelinePositions[lo-1],b=timelinePositions[lo];return timelineYears[lo-1]+(value-a)/(b-a||1);}
let scrubAnimation=null,scrubPosition=null,scrubLastTime=null,displayedPosition=null,lastChangeSignature=null,lastMilestoneSignature='';
function cancelScrub(){if(scrubAnimation!=null&&typeof cancelAnimationFrame==='function')cancelAnimationFrame(scrubAnimation);scrubAnimation=null;scrubLastTime=null;}
function queueScrub(){if(typeof requestAnimationFrame!=='function'){update();return;}if(scrubAnimation!=null)return;scrubPosition=displayedPosition??+time.value;scrubLastTime=performance.now();const step=stamp=>{const target=+time.value,elapsed=Math.max(1,stamp-scrubLastTime);scrubLastTime=stamp;scrubPosition+=(target-scrubPosition)*(1-Math.exp(-elapsed/45));if(Math.abs(target-scrubPosition)<.2)scrubPosition=target;update(scrubPosition);if(scrubPosition!==target)scrubAnimation=requestAnimationFrame(step);else{scrubAnimation=null;scrubLastTime=null;}};scrubAnimation=requestAnimationFrame(step);}
function currentYear(){return yearForPosition(time.value);}
function setYear(year){cancelScrub();time.value=positionForYear(year);update(positionForYear(year));}
let selectedStory=null;
function highlightSelection(record,type){for(const el of world.querySelectorAll('.selectionFocus'))el.classList.remove('selectionFocus');if(!record)return;const focus=el=>el?.classList.add('selectionFocus');if(type==='movement')focus(rendered.movements.get(record.id));if(type==='destruction')focus(rendered.destructions.get(record.id));if(type==='change')focus(rendered.conversions.get(record.id));if(type==='event')focus(rendered.events.get(record.id));for(const p of DATA.populations)if((type==='population'&&p.id===record.id)||p.id===record.populationId||(type==='movement'&&[record.origin,record.destination].includes(p.place))){const els=rendered.populations.get(p.id);focus(els.node);focus(els.label);focus(els.density);}}
function showStory(record,type){stopTour();highlightSelection(record,type);selectedStory={record,type,year:Math.round(continuousYear(displayedPosition??+time.value))};q('sd').textContent=record.date||'';q('st').textContent=record.title||record.historicalPlaceName||'';q('ss').textContent=record.story||record.notes||'';q('sc').textContent='';const extra=[];if(type==='population'){const state=resolvePopulation(record,currentYear());extra.push('Presence: '+state.presenceStatus+'. Concentration: '+state.concentration+'.');const latest=state.changes.at(-1);if(latest?.story)q('ss').textContent+=' '+latest.story;}
 if(type==='movement'){const from=INDEX.places.get(record.origin)?.historicalPlaceName,to=INDEX.places.get(record.destination)?.historicalPlaceName;if(from&&to)extra.push(from+' → '+to+'.');else if(record.regionalDisplacement)extra.push('Regional displacement; destination not a permanent community.');extra.push('Movement: '+(record.movementType||record.movementDescription||'type uncertain')+'.');extra.push('Cause: '+record.cause+'.');if(record.whatRemainedAtOrigin)extra.push('At origin: '+record.whatRemainedAtOrigin);const estimate=record.reportedEstimate||(record.populationPreferred!=null||record.populationLow!=null||record.populationHigh!=null?{lowEstimate:record.populationLow,highEstimate:record.populationHigh,preferredEstimate:record.populationPreferred,unit:record.populationUnit,sourceIds:record.sourceIds}:null);if(estimate&&estimate.sourceIds?.length){let number=estimate.lowEstimate!=null&&estimate.highEstimate!=null?estimate.lowEstimate+'–'+estimate.highEstimate:estimate.preferredEstimate??estimate.lowEstimate??estimate.highEstimate;if(number!=null){q('sc').textContent='Reported: '+number+' '+(estimate.unit||'people');if(estimate.explanationOfDiscrepancy)extra.push(estimate.explanationOfDiscrepancy);}}}
 q('se').textContent=[...extra,record.evidenceStatus||record.confidence,record.notes].filter(Boolean).map(t=>/[.!?]$/.test(t.trim())?t.trim():t.trim()+'.').join(' ');renderStoryEvidence(record,type);story.classList.add('show');positionStory(record,type);}
function update(position=+time.value){displayedPosition=position;const y=continuousYear(position),frame=computeFrame(y),displayYear=Math.round(y);q('yl').textContent=yearLabel(displayYear);time.dataset.year=displayYear;time.setAttribute('aria-valuetext',yearLabel(displayYear));for(const state of frame.populations){const els=rendered.populations.get(state.id);if(els.underlay)els.underlay.style.opacity=state.intensity*.5;if(els.density){vis(els.density,state.intensity);els.density.style.fill=state.uncertain?'url(#uncertainPopulationPattern)':'';els.density.classList.toggle('uncertainPopulation',state.uncertain);}if(els.node){vis(els.node,state.nodeOpacity);els.node.classList.toggle('uncertainPresence',state.uncertain);}if(els.label)vis(els.label,state.nodeOpacity>.08?1:0);}
 for(const m of frame.movements){const record=DATA.movements.find(r=>r.id===m.id),past=trailsEnabled&&m.visible&&movementWindow(record)[1]<=y;vis(rendered.movements.get(m.id),Math.max(m.opacity,past?.28:0));}for(const c of frame.destructions){const symbol=rendered.destructions.get(c.id);const record=DATA.communityDestructions.find(r=>r.id===c.id),past=trailsEnabled&&record.startDate<=y;vis(symbol,c.visible?1:past?.5:0);if(symbol?._leader)symbol._leader.style.visibility=c.visible||past?'visible':'hidden';}for(const e of frame.events){const event=rendered.events.get(e.id);vis(event,e.opacity);if(event?._label)vis(event._label,e.opacity>.08?1:0);}
 for(const [id,symbol] of rendered.conversions){const change=DATA.populationChanges.find(c=>c.id===id),visible=activeAt(change,y),past=trailsEnabled&&change.startDate<=y;vis(symbol,visible?1:past?.5:0);symbol._leader.style.visibility=visible||past?'visible':'hidden';}
 q('el').textContent=frame.era?.title||'';renderMeanwhile(y);applyMapCamera(y);
 const latest=new Map();for(const c of frame.changes){const before=latest.get(c.populationId);if(!before||before.startDate<c.startDate)latest.set(c.populationId,c);}const changes=[...latest.values()].sort((a,b)=>b.startDate-a.startDate),row=q('declineReasons'),signature=changes.map(c=>c.id).join('|');if(signature!==lastChangeSignature){lastChangeSignature=signature;row.replaceChildren();q('declineNotice').hidden=changes.length===0;for(const c of changes){const b=document.createElement('button');b.type='button';b.className='reason '+(c.populationChangeCause==='violent destruction'?'mass_killing':c.populationChangeCause==='evidence becomes uncertain'?'uncertain':'');const icon=document.createElement('span');icon.className='reasonIcon';icon.textContent=c.populationChangeCause==='evidence becomes uncertain'?'◌':'ⓘ';icon.setAttribute('aria-hidden','true');b.appendChild(icon);b.appendChild(document.createTextNode(c.label||c.title||c.populationChangeCause));b.addEventListener('click',()=>showStory(c,'change'));row.appendChild(b);}}syncMilestone(displayYear);if(story.classList.contains('show')&&selectedStory&&selectedStory.year!==displayYear)showStory(selectedStory.record,selectedStory.type);
}
function replaceData(data){assertHistory(data);if(mapNavigation.frame!=null)cancelAnimationFrame(mapNavigation.frame);mapNavigation.frame=null;labelLayoutKey='';mapNavigation.manual=false;mapNavigation.view=null;mapNavigation.pointers.clear();q('followMap').setAttribute('aria-pressed','true');stopTour();cancelScrub();lastChangeSignature=null;lastMilestoneSignature="";DATA=data;INDEX=indexData(DATA);selectedStory=null;story.classList.remove('show');renderRecords();buildTimeline();setYear(DATA.timeline.start);window.HISTORY_DATA=DATA;}

// Presentation controls are independent of evidence and historical datasets.
let tourPlaying=false,tourAnimation=null,tourPreviousTime=null;
function dismissPrompt(){const el=q('openingPrompt');if(el)el.hidden=true;const play=q('playTour');if(play)play.hidden=false;}
function stopTour(){if(!tourPlaying)return;tourPlaying=false;if(tourAnimation!=null)cancelAnimationFrame(tourAnimation);tourAnimation=null;tourPreviousTime=null;const b=q('playTour');if(b){b.textContent='▶ Play';b.setAttribute('aria-pressed','false');b.setAttribute('aria-label','Play 20-second timeline tour');}}
function startTour(){stopTour();cancelScrub();followHistory();dismissPrompt();closeStory();if(+time.value>=DATA.timeline.range-1)setYear(DATA.presentation?.openingYear??DATA.timeline.start);tourPlaying=true;const b=q('playTour');b.textContent='Ⅱ Pause';b.setAttribute('aria-pressed','true');b.setAttribute('aria-label','Pause timeline tour');tourPreviousTime=performance.now();const from=displayedPosition??+time.value;let position=from;const distance=DATA.timeline.range-from;const step=stamp=>{if(!tourPlaying)return;position=from+(stamp-tourPreviousTime)*distance/(DATA.presentation?.tourDurationMs||20000);time.value=Math.min(DATA.timeline.range,position);update(Math.min(DATA.timeline.range,position));if(position>=DATA.timeline.range){stopTour();return;}tourAnimation=requestAnimationFrame(step);};tourAnimation=requestAnimationFrame(step);}
let milestones=[];
function evidenceFor(record){if(record.evidenceStatus==='traditional account'||record.presenceStatus==='traditional')return {label:'Biblical tradition',kind:'traditional'};const kinds=record.evidenceKinds||[];if(kinds.includes('archaeological'))return {label:'Archaeological',kind:'archaeological'};if(kinds.includes('documentary'))return {label:'Documentary',kind:'documentary'};const sources=(record.sourceIds||[]).map(id=>INDEX.sources.get(id)).filter(Boolean);if(sources.some(s=>s.evidenceType==='primary/contemporary evidence'))return {label:'Historical account',kind:'documentary'};if(sources.some(s=>s.evidenceType==='academic scholarship'))return {label:'Academic scholarship',kind:'scholarship'};return {label:'Historical evidence',kind:'historical'};}
function sourceRecords(record,type){const ids=new Set(record.sourceIds||[]);if(type==='population')for(const c of computeFrame(currentYear()).changes.filter(c=>c.populationId===record.id))for(const id of c.sourceIds||[])ids.add(id);return [...ids].map(id=>INDEX.sources.get(id)).filter(Boolean);}
function renderStoryEvidence(record,type){const evidence=evidenceFor(record),badge=q('storyEvidenceBadge');badge.textContent=evidence.label;badge.className='evidenceBadge '+evidence.kind;badge.title='Evidence type; confidence and uncertainties are explained below.';const list=q('storySourceList'),wasOpen=!list.hidden;list.replaceChildren();const sources=sourceRecords(record,type);q('storySources').textContent='Sources ('+sources.length+')';q('storySources').disabled=sources.length===0;for(const source of sources){const item=document.createElement(source.url?'a':'span');if(source.url){item.href=source.url;item.target='_blank';item.rel='noopener';}item.textContent=source.title||source.id;list.appendChild(item);const caption=document.createElement('small');caption.textContent=source.evidenceType||'Source classification not supplied';list.appendChild(caption);if(source.supports){const support=document.createElement('small');support.textContent='Supports: '+source.supports;list.appendChild(support);}if(source.limitations){const limits=document.createElement('small');limits.textContent='Limits: '+source.limitations;list.appendChild(limits);}}if(!sources.length){const note=document.createElement('p');note.textContent='No source references supplied for this record.';list.appendChild(note);}list.hidden=!wasOpen;}
function renderNotches(){const box=q('eventNotches');if(!box)return;box.replaceChildren();milestones=[];const add=(collection,type)=>{for(const record of collection){const date=type==='movement'?(record.dateRange?.start??record.rendering?.window?.[1]):type==='event'?record.dateRange?.start:record.startDate;if(Number.isFinite(date)&&date>=DATA.timeline.start&&date<=DATA.timeline.end)milestones.push({record,type,date,illustrative:type==='movement'&&!Number.isFinite(record.dateRange?.start)});}};add(DATA.populations,'population');add(DATA.movements,'movement');add(DATA.historicalEvents,'event');add(DATA.communityDestructions,'destruction');add(DATA.populationChanges,'change');milestones.sort((a,b)=>a.date-b.date);const select=q('milestoneSelect');select.replaceChildren();for(let i=0;i<milestones.length;i++){const m=milestones[i],option=document.createElement('option');option.value=i;option.textContent=(m.record.date||yearLabel(m.date))+' · '+(m.record.title||m.record.historicalPlaceName||m.record.id);select.appendChild(option);}const seen=new Set();for(let i=0;i<milestones.length;i++){const m=milestones[i];if(seen.has(m.date))continue;seen.add(m.date);const el=document.createElement('button');el.type='button';el.className='eventNotch';el.style.left=positionForYear(m.date)/DATA.timeline.range*100+'%';el.dataset.year=m.date;el.setAttribute('aria-label',(m.illustrative?'Illustrative position; '+m.record.date:m.record.date||yearLabel(m.date))+': '+(m.record.title||m.record.historicalPlaceName));el.title=el.getAttribute('aria-label');el.addEventListener('click',()=>selectMilestone(i,true));box.appendChild(el);}lastMilestoneSignature='';}
function selectMilestone(index,open){const m=milestones[index];if(!m)return;stopTour();dismissPrompt();setYear(m.date);syncMilestone(m.date,index);if(open)showStory(m.record,m.type);}
function syncMilestone(year,chosen){if(!milestones.length)return;let i=chosen??0;if(chosen==null)for(let n=0;n<milestones.length;n++){if(milestones[n].date<=year)i=n;else break;}const m=milestones[i],signature=m.type+':'+m.record.id;if(signature===lastMilestoneSignature)return;lastMilestoneSignature=signature;for(const option of q('milestoneSelect').options)option.selected=+option.value===i;q('previousEvent').disabled=i===0;q('nextEvent').disabled=i===milestones.length-1;const evidence=evidenceFor(m.record),row=q('milestoneEvidence');row.replaceChildren();const badge=document.createElement('span');badge.className='evidenceBadge '+evidence.kind;badge.textContent=evidence.label;badge.title='Evidence type, not a certainty rating';row.appendChild(badge);const sources=document.createElement('button');sources.type='button';sources.className='sourcesButton';sources.textContent='Sources';sources.addEventListener('click',()=>{showStory(m.record,m.type);q('storySourceList').hidden=false;});row.appendChild(sources);const qualification=document.createElement('span');qualification.className='qualification';qualification.textContent=m.illustrative?'Exact date uncertain; position is illustrative.':m.record.evidenceStatus||m.record.confidence||'';row.appendChild(qualification);for(const notch of q('eventNotches').children)notch.classList.toggle('selected',+notch.dataset.year===m.date);}
let labelLayoutKey='',labelMetrics=new WeakMap();
const mapNavigation={manual:false,view:null,pointers:new Map(),frame:null,suppressUntil:0,dragDistance:0,rect:null};
function renderMeanwhile(year){q('meanwhile').hidden=true;return;const slot=q('meanwhile');if(!slot)return;const context=(DATA.presentation?.worldContext||[]).find(r=>r.startDate<=year&&(r.endDate==null||year<=r.endDate));const signature=context?JSON.stringify(context):'';if(slot.dataset.contextId===signature)return;slot.dataset.contextId=signature;slot.hidden=!context;const caption=slot.querySelector('span');caption.textContent=context?.text||'';slot.title=context?.evidence||'';for(const id of context?.sourceIds||[]){const source=INDEX.sources.get(id);if(!source?.url)continue;const link=document.createElement('a');link.href=source.url;link.target='_blank';link.rel='noopener';link.textContent='Source';link.title=source.title;caption.appendChild(link);}}
function declutterMapLabels(view){
 const box=world.ownerSVGElement.getBoundingClientRect?.()||{width:1200,height:650},key=view.map(v=>v.toFixed(3)).join(',')+'|'+box.width+'|'+box.height+'|'+[...rendered.populations.values()].map(p=>p.label?.style.opacity>.08?1:0).join('')+'|'+[...rendered.destructions.values(),...rendered.conversions.values()].map(p=>p.style.opacity>.08?1:0).join('')+'|'+(selectedStory?.record.id||'');if(key===labelLayoutKey)return;labelLayoutKey=key;
 const rect=world.ownerSVGElement.parentElement.getBoundingClientRect?.()||{width:1200,height:650},unit=view[2]/(rect.width||1200),occupied=[],inside=b=>b.x>=view[0]+5*unit&&b.y>=view[1]+5*unit&&b.x+b.w<=view[0]+view[2]-5*unit&&b.y+b.h<=view[1]+view[3]-5*unit,collides=b=>occupied.some(a=>b.x<a.x+a.w+3*unit&&b.x+b.w+3*unit>a.x&&b.y<a.y+a.h+3*unit&&b.y+b.h+3*unit>a.y);
 // Community anchors are protected; badges may move, but their leaders retain the true location.
 for(const node of [...rendered.populations.values()].map(p=>p.node).concat([...rendered.events.values()])){if(!node?._anchor||+(node.style.opacity||0)<=.08)continue;const [x,y]=node._anchor;occupied.push({x:x-6*unit,y:y-6*unit,w:12*unit,h:12*unit});}
 for(const symbol of [...rendered.destructions.values(),...rendered.conversions.values()]){if(+(symbol.style.opacity||0)<=.08)continue;const [ax,ay]=symbol._anchor,r=11*unit;let chosen=[ax,ay];const preferAbove=DATA.populations.find(p=>p.id===symbol._record?.populationId)?.rendering?.labelSide==='below';for(const [dx,dy] of [...(preferAbove?[[0,-24]]:[]),[0,0],[0,24],[24,0],[-24,0],[0,-24],[22,22],[-22,22],[22,-22],[-22,-22]]){const x=ax+dx*unit,y=ay+dy*unit,b={x:x-r,y:y-r,w:2*r,h:2*r};if(inside(b)&&!collides(b)){chosen=[x,y];occupied.push(b);break;}}symbol.setAttribute('transform',`translate(${chosen}) scale(${r/17})`);symbol._leader.setAttribute('d',Math.hypot(chosen[0]-ax,chosen[1]-ay)>unit?`M ${ax},${ay} L ${chosen}`:'');}
 const labels=[...world.querySelectorAll('#labelLayer .place,#geoLabels text')].sort((a,b)=>Number(b.parentElement.classList.contains('selectionFocus'))-Number(a.parentElement.classList.contains('selectionFocus'))||Number(b.classList.contains('place'))-Number(a.classList.contains('place')));
 for(const label of labels){if(typeof label.getBBox!=='function')continue;const city=label.classList.contains('place'),group=label.parentElement;if(city&&+(group.style.opacity||0)<=.08){label.style.visibility='hidden';group._leader.style.visibility='hidden';continue;}if(!label.dataset.originalX){label.dataset.originalX=label.getAttribute('x');label.dataset.originalY=label.getAttribute('y');}const target=city?14:label.classList.contains('waterLabel')?12:11;label.style.fontSize=target*unit+'px';label.style.strokeWidth=(city?4:1.5)*unit+'px';label.style.letterSpacing=city?'0':.6*unit+'px';let metrics=labelMetrics.get(label);if(!metrics){const measured=label.getBBox();metrics={w:measured.width/(target*unit),h:measured.height/(target*unit)};labelMetrics.set(label,metrics);}const w=metrics.w*target*unit,h=metrics.h*target*unit,anchor=group._anchor;let tries=[[+label.dataset.originalX,+label.dataset.originalY]];
 if(city&&anchor){const [x,y]=anchor;tries=[];for(const distance of [10,18,26])for(const [dx,dy] of [[distance,-9],[distance,21],[-distance-w/unit,-9],[-distance-w/unit,21],[-w/unit/2,-distance],[-w/unit/2,distance+14]])tries.push([x+dx*unit,y+dy*unit]);}
 if(city&&anchor&&group._labelSide)tries.sort((a,b)=>{const score=p=>group._labelSide==='left'?(p[0]<anchor[0]?0:1):(p[1]>anchor[1]?0:1);return score(a)-score(b);});if(group._labelOffset&&city&&anchor&&(!group._labelSide||(group._labelSide==='left'&&group._labelOffset[0]<0)||(group._labelSide==='below'&&group._labelOffset[1]>0)))tries.unshift([anchor[0]+group._labelOffset[0]*unit,anchor[1]+group._labelOffset[1]*unit]);let accepted=false;for(const [x,y] of tries){const left=city?x:x-w/2,b={x:left-2*unit,y:y-h-2*unit,w:w+4*unit,h:h+4*unit};if(!inside(b)||collides(b))continue;label.setAttribute('x',x);label.setAttribute('y',y);occupied.push(b);accepted=true;if(city&&anchor){group._labelOffset=[(x-anchor[0])/unit,(y-anchor[1])/unit];const lx=Math.max(x,Math.min(x+w,anchor[0])),ly=y-h*.4;group._leader.setAttribute('d',Math.hypot(lx-anchor[0],ly-anchor[1])>19*unit?`M ${anchor} L ${lx},${ly}`:'');group._leader.style.visibility='visible';}break;}label.style.visibility=accepted?'visible':'hidden';if(city&&!accepted)group._leader.style.visibility='hidden';
 }
}
function applyMapCamera(y){if(mapNavigation.manual&&mapNavigation.view){clampMapView();paintMapView(mapNavigation.view);return;}const map=world.ownerSVGElement,box=map.parentElement.getBoundingClientRect?.()||{width:1200,height:650},ratio=(box.width||1200)/Math.max(1,box.height||650),states=DATA.cameraStates;let i=0;while(i+1<states.length&&states[i+1].startDate<=y)i++;const a=states[i];if(Array.isArray(a.viewBox)&&a.viewBox.length===4){map.setAttribute('viewBox',a.viewBox.join(' '));declutterMapLabels(a.viewBox);world.style.transform='none';map.dataset.scope=a.scope||'';return;}const b=states[Math.min(i+1,states.length-1)],span=b.startDate-a.startDate,t=span>0?Math.min(1,Math.max(0,(y-a.startDate)/span)):0,eased=t*t*(3-2*t),mix=(key,fallback)=>{const av=a[key]??fallback,bv=b[key]??av;return av+(bv-av)*eased;},scale=mix('scale',1),cx=mix('centerX',600),cy=mix('centerY',325),w=ratio<1?Math.max(380,500/scale):1200/scale,h=w/Math.max(.3,ratio);const view=[cx-w/2,cy-h/2,w,h];map.setAttribute('viewBox',view.join(' '));declutterMapLabels(view);world.style.transform='none';map.dataset.scope=a.scope||'';}
function initPublicControls(){const legend=q('mapLegend'),toggle=q('legendToggle'),contents=q('legendContents');const collapse=closed=>{contents.hidden=closed;legend.classList.toggle('collapsed',closed);toggle.setAttribute('aria-expanded',String(!closed));toggle.querySelector('span').textContent=closed?'+':'−';};toggle.addEventListener('click',()=>collapse(!contents.hidden));collapse(true);q('storySources').addEventListener('click',()=>{q('storySourceList').hidden=!q('storySourceList').hidden;});q('milestoneSelect').addEventListener('change',()=>selectMilestone(+q('milestoneSelect').value,true));q('previousEvent').addEventListener('click',()=>selectMilestone(+q('milestoneSelect').value-1,true));q('nextEvent').addEventListener('click',()=>selectMilestone(+q('milestoneSelect').value+1,true));q('playTour').setAttribute('aria-pressed','false');q('playTour').addEventListener('click',()=>tourPlaying?stopTour():startTour());document.addEventListener('pointerdown',e=>{if(e.target.closest?.('#introPlay,#walkJourney'))return;dismissPrompt();},{capture:true});q('introPlay').addEventListener('click',startTour);document.addEventListener('keydown',e=>{if(['Enter',' ','ArrowLeft','ArrowRight','Home','End'].includes(e.key))dismissPrompt();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();});window.addEventListener('resize',()=>applyMapCamera(currentYear()));window.HISTORY_PRESENTATION={startTour,stopTour,continuousYear,queueScrub,selectMilestone,evidenceFor,get milestones(){return milestones;},get playing(){return tourPlaying;},dismissPrompt,applyMapCamera};}

let trailsEnabled=false;
function setTrails(enabled){trailsEnabled=!!enabled;q('trailToggle').setAttribute('aria-pressed',String(trailsEnabled));q('trailStatus').textContent=trailsEnabled?'Earlier events retained':'Selected moment';labelLayoutKey='';update(displayedPosition??+time.value);}
function closeStory(){story.classList.remove('show');highlightSelection(null);selectedStory=null;labelLayoutKey='';}
function resetJourney(){stopTour();cancelScrub();closeStory();dismissPrompt();followHistory();setYear(DATA.timeline.start);const anchor=INDEX.places.get('place-j').coordinates,rect=q('historicalMap').getBoundingClientRect(),width=rect.width<700?480:1000;mapNavigation.manual=true;mapNavigation.view=[anchor[0]-width/2,anchor[1]-width*rect.height/rect.width/2,width,width*rect.height/rect.width];paintMapView(mapNavigation.view);}
function positionStory(record,type){if(typeof innerWidth==='undefined'||innerWidth<=700)return;const place=INDEX.places.get(record.place||record.destination),anchor=record.coordinates||place?.coordinates||record.rendering?.position;if(!anchor){story.style.left='12px';story.style.right='auto';return;}const map=q('historicalMap'),v=map.getAttribute('viewBox').split(' ').map(Number),width=map.getBoundingClientRect().width,screenX=(anchor[0]-v[0])/v[2]*width;story.style.left=screenX>width/2?'12px':'auto';story.style.right=screenX>width/2?'auto':'12px';labelLayoutKey='';declutterMapLabels(v);}
function sizeMapFrame(){if(typeof innerHeight==='undefined')return;const map=q('historicalMap').parentElement,header=document.querySelector('header'),controls=document.querySelector('.controls'),isPhone=innerWidth<=700;if(isPhone){if(story.parentElement!==map.parentElement)controls.before(story);}else if(story.parentElement!==map)map.appendChild(story);const controlsHeight=isPhone?0:Math.max(340,controls.getBoundingClientRect().height),available=innerHeight-header.getBoundingClientRect().height-controlsHeight-32;map.style.height=(isPhone?Math.max(240,Math.min(innerHeight*.47,510)):Math.max(220,Math.min(available,900)))+'px';}
function paintMapView(view){const map=q('historicalMap');map.setAttribute('viewBox',view.join(' '));declutterMapLabels(view);world.style.transform='none';}
function captureManualView(){if(!mapNavigation.manual){const v=q('historicalMap').getAttribute('viewBox').split(' ').map(Number);mapNavigation.view=v;mapNavigation.manual=true;closeStory();}q('followMap').setAttribute('aria-pressed','false');stopTour();}
function clampMapView(){const v=mapNavigation.view,r=q('historicalMap').getBoundingClientRect(),ratio=r.width/Math.max(1,r.height),maxW=Math.min(5400,2207.5472*ratio);v[2]=Math.max(130,Math.min(maxW,v[2]));v[3]=v[2]/ratio;v[0]=Math.max(-2475,Math.min(2925-v[2],v[0]));v[1]=Math.max(-392.4528,Math.min(1815.0944-v[3],v[1]));}
function scheduleMapPaint(){clampMapView();if(mapNavigation.frame!=null)return;mapNavigation.frame=requestAnimationFrame(()=>{mapNavigation.frame=null;paintMapView(mapNavigation.view);});}
function zoomMap(factor,clientX,clientY){captureManualView();const r=q('historicalMap').getBoundingClientRect(),v=mapNavigation.view,fx=clientX==null?.5:(clientX-r.left)/r.width,fy=clientY==null?.5:(clientY-r.top)/r.height,px=v[0]+fx*v[2],py=v[1]+fy*v[3];v[2]*=factor;v[3]*=factor;v[0]=px-fx*v[2];v[1]=py-fy*v[3];scheduleMapPaint();}
function followHistory(){if(mapNavigation.frame!=null)cancelAnimationFrame(mapNavigation.frame);mapNavigation.frame=null;mapNavigation.manual=false;mapNavigation.view=null;mapNavigation.pointers.clear();q('historicalMap').classList.remove('dragging');q('followMap').setAttribute('aria-pressed','true');applyMapCamera(continuousYear(displayedPosition??+time.value));}
function initMapNavigation(){const map=q('historicalMap'),surface=map.parentElement;q('zoomIn').addEventListener('click',()=>zoomMap(.8));q('zoomOut').addEventListener('click',()=>zoomMap(1.25));q('followMap').addEventListener('click',resetJourney);
 map.addEventListener('wheel',e=>{e.preventDefault();dismissPrompt();zoomMap(Math.exp(Math.max(-100,Math.min(100,e.deltaY))*.002),e.clientX,e.clientY);},{passive:false});
 map.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;stopTour();mapNavigation.rect=map.getBoundingClientRect();mapNavigation.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});mapNavigation.dragDistance=0;mapNavigation.suppressUntil=0;e.preventDefault();});
 surface.addEventListener('pointermove',e=>{const old=mapNavigation.pointers.get(e.pointerId);if(!old)return;const before=[...mapNavigation.pointers.values()];mapNavigation.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const after=[...mapNavigation.pointers.values()],dx=e.clientX-old.x,dy=e.clientY-old.y;mapNavigation.dragDistance+=Math.hypot(dx,dy);if(mapNavigation.dragDistance<4&&after.length<2)return;surface.setPointerCapture?.(e.pointerId);captureManualView();map.classList.add('dragging');const v=mapNavigation.view,r=mapNavigation.rect;if(after.length===1){v[0]-=dx*v[2]/r.width;v[1]-=dy*v[3]/r.height;}else{const center=p=>({x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}),a=center(before),b=center(after),distance=p=>Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);v[0]-=(b.x-a.x)*v[2]/r.width;v[1]-=(b.y-a.y)*v[3]/r.height;zoomMap(Math.max(.5,Math.min(2,distance(before)/Math.max(1,distance(after)))),b.x,b.y);}scheduleMapPaint();e.preventDefault();});
 const release=e=>{if(!mapNavigation.pointers.has(e.pointerId))return;mapNavigation.pointers.delete(e.pointerId);if(mapNavigation.dragDistance>=4)mapNavigation.suppressUntil=performance.now()+400;if(!mapNavigation.pointers.size)map.classList.remove('dragging');};surface.addEventListener('pointerup',release);surface.addEventListener('pointercancel',release);surface.addEventListener('lostpointercapture',release);window.addEventListener('blur',()=>{mapNavigation.pointers.clear();map.classList.remove('dragging');stopTour();});map.addEventListener('click',e=>{if(performance.now()<mapNavigation.suppressUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
 window.HISTORY_MAP={zoom:zoomMap,followHistory,reset:resetJourney,setTrails,get trails(){return trailsEnabled;},get manual(){return mapNavigation.manual;},get view(){return q('historicalMap').getAttribute('viewBox').split(' ').map(Number);}};
}
window.HISTORY_ENGINE={schemaVersion:'1.0',validate:validateHistory,computeFrame,resolvePopulation,canRenderMovement,movementColor,replaceData,getData:()=>DATA};
window.HISTORY_TIMELINE={get config(){return DATA.timeline;},positionForYear,yearForPosition,currentYear,setYear};window.HISTORY_DATA=DATA;
story.addEventListener('click',e=>e.stopPropagation());document.querySelector('.map').addEventListener('click',e=>{if(!e.target.closest?.('.route,.biblical,g[data-title],.density[data-title],.story,.reason'))closeStory();});q('closeStory').addEventListener('click',closeStory);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeStory();});time.addEventListener('keydown',e=>{const delta={ArrowLeft:-1,ArrowDown:-1,ArrowRight:1,ArrowUp:1,PageDown:-10,PageUp:10};if(e.key in delta){e.preventDefault();setYear(currentYear()+delta[e.key]);}else if(e.key==='Home'||e.key==='End'){e.preventDefault();setYear(e.key==='Home'?DATA.timeline.start:DATA.timeline.end);}});time.addEventListener('input',()=>{stopTour();dismissPrompt();queueScrub();});time.addEventListener('pointerdown',stopTour);time.addEventListener('keydown',stopTour);
renderRecords();buildTimeline();setYear(DATA.presentation?.openingYear??DATA.timeline.start);initPublicControls();initMapNavigation();sizeMapFrame();applyMapCamera(currentYear());q('trailToggle').addEventListener('click',()=>setTrails(!trailsEnabled));q('walkJourney').addEventListener('click',()=>{dismissPrompt();q('sliderHint').hidden=false;q('time').focus();q('time').classList.add('sliderAttention');});q('time').addEventListener('input',()=>{q('sliderHint').hidden=true;q('time').classList.remove('sliderAttention');});window.addEventListener('resize',()=>{sizeMapFrame();applyMapCamera(continuousYear(displayedPosition??+time.value));});
