// Ported verbatim from Alpha 1.13 app.js: data validation, frame resolution and evidence rules.
const ENUMS={presence:['documented','probable','uncertain','traditional'],provenance:['documented movement','plausible','unknown'],continuity:['growing','stable','contracting','evidence becomes uncertain','documented displacement','documented destruction'],evidence:['well documented','historically established, details uncertain','reconstructed','traditional account'],concentration:['very small','small','substantial','major','dominant center'],movementType:['forced removal','expulsion','flight','voluntary migration','return / Aliyah'],cause:['war','conquest','persecution','antisemitic violence','economic opportunity','trade','religious motivation','political/national movement','family/community ties','other','uncertain'],changeCause:['natural increase','forced conversion','documented displacement','violent destruction','mortality','evidence becomes uncertain','display transition','other','uncertain']};
function validateHistory(data){
 const errors=[],required=['places','populations','populationChanges','movements','communityDestructions','historicalEvents','sources','eras','cameraStates'];
 const fail=m=>errors.push(m),finite=x=>typeof x==='number'&&Number.isFinite(x),coords=x=>Array.isArray(x)&&x.length===2&&x.every(finite);
 for(const key of required)if(!Array.isArray(data[key]))fail(key+' must be an array');if(errors.length)return errors;
 const sets={};for(const key of required){const ids=new Set();for(const r of data[key]){if(!r.id&&!['eras','cameraStates'].includes(key))fail(key+': missing id');if(r.id&&ids.has(r.id))fail(key+': duplicate id '+r.id);if(r.id)ids.add(r.id);}sets[key]=ids;}
 const places=new Map(data.places.map(p=>[p.id,p]));
 function hasEnum(value,key,name){if(!ENUMS[key].includes(value))fail(name+': invalid '+key+' '+value);}
 function refs(r){for(const id of r.sourceIds||[])if(!sets.sources.has(id))fail(r.id+': unknown source '+id);}
 function dates(r){if(!finite(r.startDate))fail(r.id+': invalid startDate');if(r.endDate!=null&&(!finite(r.endDate)||r.endDate<r.startDate))fail(r.id+': invalid endDate');}
 function estimate(e,id){if(!e)return;for(const k of ['lowEstimate','highEstimate','preferredEstimate'])if(e[k]!=null&&(!finite(e[k])||e[k]<0))fail(id+': invalid '+k);if(e.lowEstimate!=null&&e.highEstimate!=null&&e.lowEstimate>e.highEstimate)fail(id+': reversed estimate range');if(e.preferredEstimate!=null&&((e.lowEstimate!=null&&e.preferredEstimate<e.lowEstimate)||(e.highEstimate!=null&&e.preferredEstimate>e.highEstimate)))fail(id+': preferred estimate outside range');if([e.lowEstimate,e.highEstimate,e.preferredEstimate].some(v=>v!=null)&&!(e.sourceIds||[]).length)fail(id+': numbered estimate requires sources');}
 for(const p of data.places)if(p.coordinates!=null&&!coords(p.coordinates))fail(p.id+': invalid coordinates');
 for(const p of data.populations){dates(p);refs(p);hasEnum(p.presenceStatus,'presence',p.id);hasEnum(p.provenanceStatus,'provenance',p.id);hasEnum(p.continuityStatus,'continuity',p.id);hasEnum(p.concentration,'concentration',p.id);if(!places.has(p.place))fail(p.id+': unknown place');if(places.get(p.place)?.role==='killing site')fail(p.id+': a killing site cannot become a population node');if(p.endDate!=null&&!['documented displacement','documented destruction','forced conversion','documented absence'].includes(p.endReason))fail(p.id+': an end date requires an explicit supported endReason');estimate(p.estimate,p.id);for(const id of p.movementIds||[])if(!sets.movements.has(id))fail(p.id+': unknown movement '+id);let prev=-Infinity;for(const s of p.states||[]){if(!finite(s.date)||s.date<prev)fail(p.id+': unsorted state dates');prev=s.date;if(s.concentration)hasEnum(s.concentration,'concentration',p.id);if(s.presenceStatus)hasEnum(s.presenceStatus,'presence',p.id);if(s.continuityStatus)hasEnum(s.continuityStatus,'continuity',p.id);}}
 for(const c of data.populationChanges){dates(c);refs(c);if(!sets.populations.has(c.populationId))fail(c.id+': unknown population');hasEnum(c.populationChangeCause,'changeCause',c.id);if(c.result?.concentration)hasEnum(c.result.concentration,'concentration',c.id);if(c.result?.presenceStatus)hasEnum(c.result.presenceStatus,'presence',c.id);if(c.result?.intensity!=null&&(!finite(c.result.intensity)||c.result.intensity<0||c.result.intensity>1))fail(c.id+': invalid visual intensity');if(c.populationChangeCause==='evidence becomes uncertain'&&c.result?.intensity===0)fail(c.id+': uncertain evidence must not erase presence');}
 for(const m of data.movements){refs(m);if(m.movementType!=null)hasEnum(m.movementType,'movementType',m.id);else if(m.movementTypeConfidence!=='uncertain')fail(m.id+': unknown movement type requires an explicit uncertainty qualification');hasEnum(m.cause,'cause',m.id);hasEnum(m.evidenceStatus,'evidence',m.id);hasEnum(m.provenanceStatus,'provenance',m.id);if(m.origin!=null&&!places.has(m.origin))fail(m.id+': unknown origin');if(m.destination!=null&&!places.has(m.destination))fail(m.id+': unknown destination');if(m.originCoordinates!=null&&!coords(m.originCoordinates))fail(m.id+': invalid origin coordinates');if(m.destinationCoordinates!=null&&!coords(m.destinationCoordinates))fail(m.id+': invalid destination coordinates');for(const id of m.intermediateLocations||[])if(!places.has(id))fail(m.id+': unknown intermediate location');for(const id of m.linkedDestructionIds||[])if(!sets.communityDestructions.has(id))fail(m.id+': unknown destruction');if(m.evidenceStatus!=='traditional account'&&m.provenanceStatus==='documented movement'&&!(m.sourceIds||[]).length)fail(m.id+': documented movement requires sources');estimate({lowEstimate:m.populationLow,highEstimate:m.populationHigh,preferredEstimate:m.populationPreferred,sourceIds:m.sourceIds},m.id);estimate(m.reportedEstimate,m.id);const w=m.rendering?.window;if(w&&(!Array.isArray(w)||w.length!==3||!w.every(finite)||w[0]>w[1]||w[1]>w[2]))fail(m.id+': invalid movement visibility window');}
 for(const c of data.communityDestructions){dates(c);refs(c);if(!sets.populations.has(c.populationId)||!places.has(c.place))fail(c.id+': unknown community or place');if(c.destructionStatus!=='documented violent community destruction')fail(c.id+': broken star requires violent destruction of the community itself');if(!(c.sourceIds||[]).length)fail(c.id+': community destruction requires sources');if(c.reestablishedDate!=null&&(!finite(c.reestablishedDate)||c.reestablishedDate<c.startDate))fail(c.id+': invalid reestablishment date');}
 for(const e of data.historicalEvents){refs(e);if(!places.has(e.place))fail(e.id+': unknown event place');}
 if(!data.timeline||!finite(data.timeline.start)||!finite(data.timeline.end)||data.timeline.start>=data.timeline.end)fail('Invalid timeline endpoints');
 return errors;
}
function assertHistory(data){const errors=validateHistory(data);if(errors.length)throw new Error('Historical dataset: '+errors.join('; '));}
function indexData(data){return {places:new Map(data.places.map(p=>[p.id,p])),sources:new Map(data.sources.map(s=>[s.id,s]))};}
function yearLabel(y){return y<0?Math.abs(y)+' BCE':y===0?'1 BCE / 1 CE':y+' CE';}
function fw(y,s,p,n){if(y<s||y>n)return 0;if(y<=p)return Math.max(.12,(y-s)/(p-s||1));return Math.max(0,1-(y-p)/(n-p||1));}
function lastState(y,states,key='date'){let found=null;for(const s of states||[])if(s[key]<=y&&(!found||s[key]>=found[key]))found=s;return found;}
function activeAt(r,y){return y>=r.startDate&&(r.endDate==null||y<r.endDate);}
function opacityAt(y,states,smooth=0){let last=-1;for(let i=0;i<(states||[]).length;i++)if(y>=states[i][0])last=i;if(last<0)return 0;const [date,value]=states[last];if(!smooth||last===0)return value;const before=states[last-1][1],t=Math.min(1,Math.max(0,(y-date)/smooth));return before+(value-before)*t;}
function movementWindow(m){if(m.rendering?.window)return m.rendering.window;const start=m.dateRange?.start??m.eventDateRange?.start,end=m.dateRange?.end??start;if(!Number.isFinite(start))return null;return [start-8,(start+end)/2,end+8];}
function canRenderMovement(m,data=DATA){if(m.rendering?.enabled===false||!movementWindow(m))return false;const idx=data===DATA?INDEX:indexData(data);const origin=m.originCoordinates||idx.places.get(m.origin)?.coordinates,dest=m.destinationCoordinates||idx.places.get(m.destination)?.coordinates;return !!(origin&&dest&&(m.destination!=null||m.regionalDisplacement===true)&&(m.evidenceStatus==='traditional account'||(m.provenanceStatus==='documented movement'&&(m.sourceIds||[]).length>0&&['well documented','historically established, details uncertain'].includes(m.evidenceStatus))));}
function movementColor(m,data=DATA){const traditional=m.evidenceStatus==='traditional account';if(traditional)return '#6d6256';const destination=data.places.find(p=>p.id===m.destination);if(destination?.isLandOfIsrael)return '#275d9b';if(['forced removal','expulsion','flight'].includes(m.movementType)||['persecution','antisemitic violence'].includes(m.cause))return '#a33b32';return '#6d6256';}
function resolvePopulation(p,y,data=DATA){
 const status={presenceStatus:p.presenceStatus,concentration:p.concentration,continuityStatus:p.continuityStatus,...lastState(y,p.states)};
 const applicable=data.populationChanges.filter(c=>c.populationId===p.id&&activeAt(c,y)).sort((a,b)=>a.startDate-b.startDate);
 for(const c of applicable)if(c.result)Object.assign(status,c.result);
 const render=p.rendering||{},within=y>=p.startDate&&(p.endDate==null||y<=p.endDate)&&y>=(render.displayStart??-Infinity)&&(render.displayEnd==null||y<render.displayEnd);
 let intensity=render.densityOpacityStates?.length?opacityAt(y,render.densityOpacityStates,render.transitionYears||0):data.concentrationStyles?.[status.concentration]??.28;
 let nodeOpacity=render.nodeOpacityStates?.length?opacityAt(y,render.nodeOpacityStates):1;
 if(render.nodeRamp){const [start,duration,base,end=Infinity]=render.nodeRamp;if(y>=start&&y<=end)nodeOpacity=Math.min(1,(y-start)/duration+base);}
 if(!render.densityOpacityStates?.length){const categoryStates=[[p.startDate,data.concentrationStyles?.[p.concentration]??.28],...(p.states||[]).filter(s=>s.concentration).map(s=>[s.date,data.concentrationStyles?.[s.concentration]??.28])].sort((a,b)=>a[0]-b[0]);intensity=opacityAt(y,categoryStates,render.transitionYears??8);for(const c of applicable){if(c.result?.concentration){const target=data.concentrationStyles?.[c.result.concentration]??.28,t=Math.min(1,Math.max(0,(y-c.startDate)/(c.result.transitionYears??8)));intensity=intensity+(target-intensity)*t;}}}if(status.intensity!=null)intensity=status.intensity;if(status.nodeOpacity!=null)nodeOpacity=status.nodeOpacity;
 const uncertain=status.uncertain||status.presenceStatus==='uncertain'||status.continuityStatus==='evidence becomes uncertain'||(render.uncertainAfter!=null&&y>render.uncertainAfter);
 // Documentary silence cannot be rendered as extinction.
 if(uncertain&&within)intensity=Math.max(.09,intensity);
 return {id:p.id,...status,intensity:within?intensity:0,nodeOpacity:within?nodeOpacity:0,uncertain:!!uncertain,visible:within,changes:applicable};
}
function computeFrame(y,data=DATA){
 return {year:y,populations:data.populations.map(p=>resolvePopulation(p,y,data)),movements:data.movements.map(m=>({id:m.id,visible:canRenderMovement(m,data),opacity:canRenderMovement(m,data)?fw(y,...(movementWindow(m)||[0,0,0]))*(m.rendering?.opacity??1):0,color:movementColor(m,data)})),destructions:data.communityDestructions.map(c=>({id:c.id,visible:c.destructionStatus==='documented violent community destruction'&&activeAt(c,y)&&(c.reestablishedDate==null||y<c.reestablishedDate)})),events:data.historicalEvents.map(e=>({id:e.id,opacity:e.rendering?.window?fw(y,...e.rendering.window):0})),changes:data.populationChanges.filter(c=>activeAt(c,y)),camera:lastState(y,data.cameraStates,'startDate'),era:lastState(y,data.eras,'startDate')};
}
function canRenderConversion(change){return change.populationChangeCause==='forced conversion'&&(change.sourceIds||[]).length>0&&['well documented','historically established, details uncertain'].includes(change.evidenceStatus);}
function evidenceFor(record){if(record.evidenceStatus==='traditional account'||record.presenceStatus==='traditional')return {label:'Biblical tradition',kind:'traditional'};const kinds=record.evidenceKinds||[];if(kinds.includes('archaeological'))return {label:'Archaeological',kind:'archaeological'};if(kinds.includes('documentary'))return {label:'Documentary',kind:'documentary'};const sources=(record.sourceIds||[]).map(id=>INDEX.sources.get(id)).filter(Boolean);if(sources.some(s=>s.evidenceType==='primary/contemporary evidence'))return {label:'Historical account',kind:'documentary'};if(sources.some(s=>s.evidenceType==='academic scholarship'))return {label:'Academic scholarship',kind:'scholarship'};return {label:'Historical evidence',kind:'historical'};}
