-- generated by tools/question_lock.py from data/history.json; 21 approved questions
DELETE FROM question_lock;
INSERT INTO question_lock (id, era, style, kind, n, correct_idx) VALUES
('Q001','Second Temple & Rome','Closer to','mc',4,1),
('Q003','Second Temple & Rome','Closer to','mc',4,0),
('Q021','Second Temple & Rome','Closer to','mc',4,1),
('Q036','Biblical era','Closer to','mc',4,1),
('Q037','Second Temple & Rome','Closer to','mc',4,1),
('Q038','Second Temple & Rome','Could have','mc',2,0),
('Q039','Second Temple & Rome','Could have','mc',2,0),
('Q040','Second Temple & Rome','Which came first?','mc',2,0),
('Q041','Second Temple & Rome','Which came first?','mc',2,0),
('Q042','Biblical era','Put these in order','order',4,NULL),
('Q043','Medieval & Modern','Put these in order','order',4,NULL),
('Q044','Second Temple & Rome','Find the impostor','mc',4,3),
('Q045','Medieval & Modern','Find the impostor','mc',4,3),
('Q046','Biblical era','Time machine','mc',4,0),
('Q047','Biblical era','Time machine','mc',4,0),
('Q048','Second Temple & Rome','All of the above','mc',5,4),
('Q049','Second Temple & Rome','All of the above','mc',5,4),
('Q050','Medieval & Modern','Same year','mc',4,0),
('Q051','Medieval & Modern','Same year','mc',4,0),
('Q052','Biblical era','Relationship pairing','mc',4,0),
('Q053','Medieval & Modern','Relationship pairing','mc',4,0);
