#!/usr/bin/env python3
"""Build the SQL that locks each approved quiz question's definition into the logger database (table question_lock).
The logger Worker reads this table, so a visitor's browser cannot claim a choice that does not exist, a wrong era or style,
or a made-up 'correct' flag. Re-run and re-apply whenever the question bank changes (see worker/README note in SETUP below).

Usage:  python3 tools/question_lock.py [data/history.json] > worker/question_lock.sql
Apply the output to the D1 database 'journeysquiz' (dashboard: D1, journeysquiz, Console; or ask Claude to apply it).
Questions not in this table are refused by the Worker (fail closed), so a new question is not logged until this is re-applied.
"""
import json, sys
path = sys.argv[1] if len(sys.argv) > 1 else 'data/history.json'
d = json.load(open(path))
LET = 'ABCDE'
rows = []
for q in d['sheet']['questions']:
    if q.get('status') != 'approved':
        continue
    order = q['correct'] == 'order'
    n = len(q['choices'])
    if not (2 <= n <= 5):
        sys.exit('question %s has %d choices' % (q['id'], n))
    if not order and q['correct'] not in LET[:n]:
        sys.exit('question %s: correct %r is not one of its %d choices' % (q['id'], q['correct'], n))
    rows.append((q['id'], q['era'], q['style'], 'order' if order else 'mc', n, None if order else LET.index(q['correct'])))
esc = lambda s: "'" + s.replace("'", "''") + "'"
print('-- generated by tools/question_lock.py from %s; %d approved questions' % (path, len(rows)))
print('DELETE FROM question_lock;')
vals = ',\n'.join('(%s,%s,%s,%s,%d,%s)' % (esc(i), esc(e), esc(s), esc(k), n, 'NULL' if c is None else c) for i, e, s, k, n, c in sorted(rows))
print('INSERT INTO question_lock (id, era, style, kind, n, correct_idx) VALUES\n%s;' % vals)
